# Generated by Django 5.0.1 on 2024-01-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='ryan',
        ),
        migrations.RemoveField(
            model_name='about',
            name='team_name',
        ),
    ]
