# Generated by Django 4.2.5 on 2023-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
