# Generated by Django 4.2.5 on 2023-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_driverprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
