# Generated by Django 4.2.5 on 2023-12-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_driverprofile_points_pointreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='points',
            new_name='selected_sponsor_id',
        ),
        migrations.CreateModel(
            name='DriverPointsForSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.driverprofile')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sponsorlist')),
            ],
        ),
    ]
